version: '3'
services:
  server:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/clothes-app
      - /clothes-app/node_modules
    ports:
      - 1337:1337

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/clothes-app
      - /clothes-app/node_modules
    ports:
      - 3000:80
    depends_on:
      - server
